on:
  push: 
  pull_request: {}
  workflow_dispatch:
    inputs:
      environment:
        description: "Github Workflow Environment"
        type: environment
        required: true

jobs:
  #https://stackoverflow.com/questions/61255989/dynamically-retrieve-github-actions-secret
  get-environment-name:
    name: Determine Github Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.extract.outputs.environment }}
    steps:
      - name: Determine if dev #commits to the default branch should be dev env
        if: github.event.ref == format('refs/heads/{0}', inputs.development-branch) || (startsWith(github.event.ref, 'refs/tags/v') && github.event.ref == format('refs/heads/{0}', inputs.development-branch))
        run: |
          echo CUSTOM_ENV=dev >> $GITHUB_ENV

      - name: Determine if prod #commits with tags on default branch should be prod env
        if: github.event.ref == format('refs/heads/{0}', inputs.development-branch) && startsWith(github.event.ref, 'refs/tags/v')
        run: |
          echo CUSTOM_ENV=prod >> $GITHUB_ENV

      - name: Override with input #always use the value provided by the workflow input if one is set
        if: "github.event.inputs.environment"
        env:
          WORKFLOW_INPUT: ${{ github.event.inputs.environment }}
        run: |
          echo CUSTOM_ENV=$WORKFLOW_INPUT  >> $GITHUB_ENV
      - name: Output selected environment
        run: |
          echo "Extracted environment name: $CUSTOM_ENV"  && echo "::set-output name=environment:: $CUSTOM_ENV"

  consume-environment:
    name: Consume the custom environment
    runs-on: ubuntu-latest
    needs: [get-environment-name]
    environment: ${{ needs.get-environment-name.outputs.environment }}
    steps:
      - name: consume environment
        run: |
          echo ${{ env.CUSTOM_ENV }} &&
          echo ${{secrets.ENVIRONMENT_VALUE}} | sed 's/./& /g'