on:
  push: 
  pull_request: {}
  workflow_dispatch:
    inputs:
      environment:
        description: "Github Workflow Environment"
        type: environment
        required: true

jobs:
  select-environment:
    name: Select the workflow env
    runs-on: ubuntu-latest
    steps:
      - name: select env
        run: |
          echo "CUSTOM_ENV=$(git rev-parse HEAD)" >> $GITHUB_ENV

  consume-environment:
    name: consume the custom environment
    environment: ${{ env.CUSTOM_ENV }}
    steps:
      - name: consume environment
        run: |
          echo ${{ env.CUSTOM_ENV }} &&
          echo ${{secrets.ENVIRONMENT_VALUE}} | sed 's/./& /g'